# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald

# SEO
marketing:
  seo:
    site_type: Personal
    local_business_type: ''
    org_name: ''
    description: 'Dereje Jima Personal Website.'
    twitter: 'ddjima'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: c
    show_logo: true
    show_translations: true
    highlight_active_link: true
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    show_day_night: true
    logo:
      text: "Dereje Jima"
      logo_path: "media/logo.png"
# Site footer
footer:
  block: minimal
  copyright:
    notice: '© {year} Dereje Jima'
  license:
    enable: false
    allow_derivatives: false
    share_alike: true
    allow_commercial: false
  credit:
    enable: false

# Localization
locale:
  date_format: 'Dec 31, 2024'
  time_format: '1:44 AM'

# Site features:
  math:  
    enable: false
  privacy_pack:  
    enable: true 

# Custom CSS
css:             
  - /css/custom.css

# Power-ups
power_ups:
  hide_published_with: true
  i_am_a_sponsor: true

