[build]
  command = "npm install && PATH=$PWD/node_modules/.bin:$PATH hugo --cleanDestinationDir --gc --minify -b https://www.ddjima.com/ && npx pagefind --site public"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.161.1"
  GO_VERSION = "1.21.5"
  NODE_VERSION = "22"
  HUGO_ENABLEGITINFO = "true"
  HUGO_EXTENDED = "true"
 

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "npm install && PATH=$PWD/node_modules/.bin:$PATH hugo --cleanDestinationDir --gc --minify --buildFuture -b $DEPLOY_PRIME_URL && npx pagefind --site public"

[context.branch-deploy]
  command = "npm install && PATH=$PWD/node_modules/.bin:$PATH hugo --cleanDestinationDir --gc --minify -b $DEPLOY_PRIME_URL && npx pagefind --site public"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

[[context.production.plugins]]
  package = "netlify-plugin-submit-sitemap"
  [context.production.plugins.inputs]
    baseUrl = "https://www.ddjima.com"
    sitemapPath = "/sitemap.xml"

[[redirects]]
  from = "http://ddjima.com/*"
  to = "https://www.ddjima.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.ddjima.com/*"
  to = "https://www.ddjima.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://ddjima.com/*"
  to = "https://www.ddjima.com/:splat"
  status = 301
  force = true
